defmodule UOF.Schemas.XML.Registry do
  @moduledoc false
  # Generated by `mix uof.schemas.gen`: every decodable root element name =>
  # its schema module. The default registry for `UOF.Schemas.XML.decode/1`.

  @all %{
    "alive" => UOF.Schemas.Feed.Alive,
    "available_selections" => UOF.Schemas.API.CustomBet.AvailableSelections,
    "bet_cancel" => UOF.Schemas.Feed.BetCancel,
    "bet_settlement" => UOF.Schemas.Feed.BetSettlement,
    "bet_stop" => UOF.Schemas.Feed.BetStop,
    "betstop_reasons_descriptions" => UOF.Schemas.API.Descriptions.BetstopReasonsDescriptions,
    "betting_status_descriptions" => UOF.Schemas.API.Descriptions.BettingStatusDescriptions,
    "bookmaker_details" => UOF.Schemas.API.Users.BookmakerDetails,
    "calculation_response" => UOF.Schemas.API.CustomBet.CalculationResponse,
    "cashout" => UOF.Schemas.API.Probability.Cashout,
    "competitor_profile" => UOF.Schemas.API.Sports.CompetitorProfileEndpoint,
    "filtered_calculation_response" => UOF.Schemas.API.CustomBet.FilteredCalculationResponse,
    "fixture_change" => UOF.Schemas.Feed.FixtureChange,
    "fixture_changes" => UOF.Schemas.API.Sports.FixtureChangesEndpoint,
    "fixtures_fixture" => UOF.Schemas.API.Sports.FixturesEndpoint,
    "market_descriptions" => UOF.Schemas.API.Descriptions.MarketDescriptions,
    "match_status_descriptions" => UOF.Schemas.API.Descriptions.MatchStatusDescriptions,
    "match_summary" => UOF.Schemas.API.Sports.MatchSummaryEndpoint,
    "match_timeline" => UOF.Schemas.API.Sports.MatchTimelineEndpoint,
    "odds_change" => UOF.Schemas.Feed.OddsChange,
    "player_profile" => UOF.Schemas.API.Sports.PlayerProfileEndpoint,
    "producers" => UOF.Schemas.API.Descriptions.Producers,
    "race_summary" => UOF.Schemas.API.Sports.StageSummaryEndpoint,
    "response" => UOF.Schemas.Common.Response,
    "result_changes" => UOF.Schemas.API.Sports.ResultChangesEndpoint,
    "rollback_bet_cancel" => UOF.Schemas.Feed.RollbackBetCancel,
    "rollback_bet_settlement" => UOF.Schemas.Feed.RollbackBetSettlement,
    "schedule" => UOF.Schemas.API.Sports.ScheduleEndpoint,
    "snapshot_complete" => UOF.Schemas.Feed.SnapshotComplete,
    "sport_categories" => UOF.Schemas.API.Sports.SportCategoriesEndpoint,
    "sport_tournaments" => UOF.Schemas.API.Sports.SportTournamentsEndpoint,
    "sports" => UOF.Schemas.API.Sports.SportsEndpoint,
    "tournament_info" => UOF.Schemas.API.Sports.TournamentInfoEndpoint,
    "tournament_seasons" => UOF.Schemas.API.Sports.TournamentSeasons,
    "tournaments" => UOF.Schemas.API.Sports.TournamentsEndpoint,
    "variant_descriptions" => UOF.Schemas.API.Descriptions.VariantDescriptions,
    "venue_summary" => UOF.Schemas.API.Sports.VenueSummaryEndpoint,
    "void_reasons_descriptions" => UOF.Schemas.API.Descriptions.VoidReasonsDescriptions
  }

  @doc "Every root element name => schema module."
  def all, do: @all
end
